apiVersion: v1
kind: Service
metadata:
  name: cars-api-web
  namespace: cars-api
  labels:
    app-name: cars-api
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    app-name: cars-api
    tier: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carsapi-web-deployment
  namespace: cars-api
  labels:
    app-name: cars-api
spec:
  selector:
    matchLabels:
      app-name: cars-api
      tier: web
  replicas: 2 # We want two pods for this deployment
  template:
    metadata:
      labels:
        app-name: cars-api
        tier: web
    spec:
      containers:
      - name: cars-api-web
        image: cars-api-web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SQL_HOST
          value: "carsapi-postgres"
        - name: SQL_PORT
          value: "5432"
        - name: SQL_PWD
          valueFrom:
            secretKeyRef:
              name: postgres-userpass
              key: root_password
        - name: SQL_USERNAME
          value: "postgres"
